### ISSUE TITLE
AGP7: Merge Aragon HQ and Community meetings

### ISSUE THREAD

**Issue by luisivan** [aragon/governance#15]
### Goals

- Replace most part of the Aragon HQ meeting with publicly-accessible slides
- Leave all discussion related to the Aragon HQ meeting to the Community meeting, in order to unify them and reduce the time we spend on calls and "office" bureaucracy 

### Description

You can learn more about our governance model [at the wiki](http://wiki.aragon.one/documentation/Community_Governance_Model/). The tl;dr about the HQ meeting is as follows:

> Discussion about the state of Aragon, near future plans and decisions that need to be made. 10 min presentations with slides from team members, in which each one will run through the most important things we have done during the month

Since we're mostly running through slides, it makes sense for all team members to just work on them and publish them online. We can publish them on Mon, and then leave the whole week for the community to review it and prepare questions for the Community meeting on Fri.

Every team member should look at each other's slides and prepare for the call, asking any questions that may have emerged. The community should do the same.

This way, we both save time in meetings, while being even more accountable, since accessing slides would be easier for the community than watching a very long call.

**Comment by shyblugs** [comment]
Great idea, I do think hearing the guys speak about what there doing adds value though

**Comment by izqui** [comment]
I completely support the idea of unifying both meetings as you propose.

Unsure if slides are still the best format for this if they are not meant to be presented. At least they would need to be much more self explanatory than the ones we have been doing. Otherwise a quick write-up by all team members might be easier to digest (going through 1 slide deck per team member doesn't scale).

**Comment by luisivan** [comment]
Agree with the idea of write-ups instead of slides. We could then get all write-ups together in a monthly blog post very easily. What do you think @Smokyish?

**Comment by shyblugs** [comment]
+1 for the writeups they don't have to be really detailed, that can probably become quite burdensome.

**Comment by Smokyish** [comment]
@luisivan The proposal sounds good, i like the idea of write-ups as well.

We could post the write-ups as a blog post where each team member would contribute, then have the Meeting agenda as a list of topics we want to discuss in the meeting, the audience could participate in the discussion via the livechat and we could do an AMA after the things listed in the agenda have been gone through.

Just unsure if we should take a small break at this point or just keep it as one continuous meeting, we'll probably need to see how long it runs first and go from there.

I hope this format would make the meetings more of a discussion than a presentation type of thing and would give the community more chance to participate.

**Comment by luisivan** [comment]
Totally agree! Let's see how the first one goes and work from there. After a week, I consider this to have enough consensus to be tried 👍

**Comment by luisivan** [comment]
Actually just before closing this, @Smokyish can you reflect this in the wiki and all other places?

**Comment by Smokyish** [comment]
Changes reflected to https://wiki.aragon.one/documentation/Community_Governance_Model/ and https://blog.aragon.one/aragons-community-governance-model-2971df8f7817

Closing the issue.
