### ISSUE TITLE
AGP13: Do your values align with those described in the Aragon Manifesto?

### ISSUE THREAD

**Issue by lkngtn** [aragon/governance#21]
We intend to use this issue along with ANT signals from the survey app to gauge community sentiment.

We would like to understand if the [Aragon Manifesto](https://blog.aragon.one/the-aragon-manifesto-4a21212eac03) as presented by the Aragon One Team aligns well with the Aragon community. Please use this issue for discussion and the Survey app to signal support, you can split your vote between yes or no to express mixed sentiment.

**Comment by yermoo** [comment]
I voted YES
This is TxHash
https://etherscan.io/tx/0xb165a96157d3ac9f1cec16a991fd80823125e82f1592a86ed72bbc7ed620f4a8

**Comment by lkngtn** [comment]
This survey has now completed.
<img width="1442" alt="luke-sc-2018-07-24-09h-42m-08s" src="https://user-images.githubusercontent.com/4986634/43153602-8d8e2290-8f26-11e8-8f21-cc55948c1768.png">
