### ISSUE TITLE
AGP14: Do you support EIP999?

### ISSUE THREAD

**Issue by lkngtn** [aragon/governance#22]
We intend to use this issue along with ANT signals from the survey app to gauge community sentiment.

We would like to understand how ANT holders feel about EIP999, as it is a significant discussion within the wider Ethereum community that impacts the Aragon project and its community members. Please use this issue for discussion and the Survey app to signal support, you can split your vote between options to express mixed sentiment.

**Comment by Smokyish** [comment]
More information as to what EIP-999 is can be found at https://eips.ethereum.org/EIPS/eip-999

**Comment by lkngtn** [comment]
This survey has completed. 
<img width="1426" alt="luke-sc-2018-07-24-09h-42m-38s" src="https://user-images.githubusercontent.com/4986634/43153637-a9e9f464-8f26-11e8-89b0-6ee025d38747.png">

**Comment by GriffGreen** [comment]
So 52 votes For yes... does that mean 52 ANT tokens? 

It would be interesting to see the breakdown of how many addresses voted.

I will definitely add this dapp to the signaling website's radar

**Comment by luisivan** [comment]
That means 53 ANT, yeah :P
