### ISSUE TITLE
AGP 16: How should the apps be sorted in the upcoming App center?

### ISSUE THREAD

**Issue by Smokyish** [aragon/governance#24]
This proposals is intended to discuss and gauge sentiment of the community on how to set the default order/sorting of apps in the upcoming App center.

- Chronologically: Latest to oldest
- Alphabetically: From A to Z
- By installations: Most installations to least installations

Many things like app stores suffer from the issue that the most popular things become popular due to how content is shown to users. This can be manipulated to fill certain needs or to better serve those who wish to abuse it, thus we should get a signal from the community on how they would like to see sorting of apps done.

**Comment by lkngtn** [comment]
This survey has now concluded. 

<img width="1431" alt="luke-sc-2018-07-24-09h-43m-28s" src="https://user-images.githubusercontent.com/4986634/43153413-1824d5da-8f26-11e8-8182-454240e05f61.png">
