### ISSUE TITLE
AGP 17: How quickly should we prioritize adding privacy features to Aragon products?

### ISSUE THREAD

**Issue by Smokyish** [aragon/governance#25]
Privacy is important, more important to others especially on a public blockchain. How quickly should be prioritize adding privacy features to Aragon products such as Aragon Core and aragonOS?

- Short-term
- Medium-term
- Long-term
- I don't care about privacy

**Comment by lkngtn** [comment]
This survey has now concluded.
<img width="1424" alt="luke-sc-2018-07-24-09h-43m-09s" src="https://user-images.githubusercontent.com/4986634/43153459-38245d2e-8f26-11e8-996c-0a587b62a017.png">
