### ISSUE TITLE
AGP 18: The Merit System -a proposal

### ISSUE THREAD

**Issue by AHIGHROLLER** [aragon/governance#27]
### Goals

 A system whereby members who themselves have a certain amount of trust (this may be negligible) may be allowed to give a subject (be it a survey or anything else) merit for relevancy, quality and/or personal feelings of a positive nature. On the other spectrum...  in cases where members come across frivolous, unjust or by their standards (Item or case in question) of unacceptable quality may take an equal amount of merit away.

- Goal 1: To prevent information, in any form, from becoming exclusionary to the judiciary foundation of Aragon.
- Goal 2: Accountability. No one individual, shall need to posses any greater amount of influence than any other. This system has a goal to keep all members equally accountable no matter their role.
- Goal 3: Quality control. This system goes beyond individual merit to each and every aspect of Aragon. If I wish to buy something on "example1 com" I most often look at consumer ratings or the like. Why? Because I need to know what to expect. The goal of Merit is just that, preventing the unexpected.

### Description

   **"The Merit System"**    As judiciary matters can be of a pressing and costly nature, merit itself must be earned in order to be given. Merit will be given from one's own personal merit "account", as well when merit is deemed necessary to be deleted, the one issuing the subtraction will need to have an appropriate "merit" balance. This is not only to ensure there will be no unjust or corrupt merit deletions, yet also because in order to subtract from another's merit, you will need to use your own as a "deposit" for a time to be set. This way if the other party feels the action was unjust they may appeal, and there will be "merit" for refunding if it is deemed to be so done. If either no injunction is filed, or the filer loses then the merit is returned. This system may have a wide range of applications for Aragon. This is an initial (and my first ever anywhere) offering which can be built upon, and I believe it will better Aragon.

### Uncertainties
   *UPDATED* 
 While I see no forseeable downside to having a system that allows everyone to vote on the merit of topics and what ever else Merit may apply to, I can always see the point where human nature and the vindictive nature of it come forth. That is why I set up the balance system, so merit is actually meaningful and not just an empty number. To give, you must really believe it is deserved, and to take, you will have undoubtedly a very good reason as it will not be a swift process. Everyone deserves a fair shot, and having a Merit system allows an equal playing field, with some fine tuning it could be a great addition. -Also Merit is not and will not be a currency, simply a point system.

**Comment by lkngtn** [comment]
Hi @AHIGHROLLER thanks for submitting this proposal! I'm not 100 percent sure I follow it completely, so going to try an summarize and you can tell me if it sounds about right?

The merit system would create some sort of reputation based curation mechanism, where users could upvote/downvote items such as surveys/proposals based on whether they think that particular content is worthwhile?

> As judiciary matters can be of a pressing and costly nature, merit itself must be earned in order to be given. Merit will be given from one's own personal merit "account", as well when merit is deemed necessary to be deleted, the one issuing the subtraction will need to have an appropriate "merit" balance. 

This part definitely confuses me, is the thinking that merit acts more of like a currency where it is passed from person to person?

**Comment by AHIGHROLLER** [comment]
Hi, sorry about the confusion. On your first point you are spot-on. To clear up any confusion Merit "could" be a currency. But in this application it would not be. (Really that bit was only for very unlikely abstract uses). The main objective is really to give quality control and at the same time allow a better system to help users find relevant material quickly and efficiently. I hope this answers everything and let ,me know if I can do anything to further help, -regards

**Comment by AHIGHROLLER** [comment]
I have updated the proposal to hopefully clear up any uncertainties. -regards

**Comment by AHIGHROLLER** [comment]
I am highly encouraged by the fact that this issue has not been closed. I am admittedly not advanced at coding, yet I am very passionate about Ethereum, Aragon and the entire concept of blockchain technology. It is my hope that with my continued education (online classes) as well as any chances to contribute to the betterment of this or any project within Aragon that I may become as skilled a developer as I know I can be. 
 I want to let you all know I will be working on this as a full time job, and if you see any way I am not fulfilling my end of things please let me know, so I may do better. Most of all thank you for the opportunity. Now...time to get to work.

**Comment by lkngtn** [comment]
> I am highly encouraged by the fact that this issue has not been closed.

We don't currently have a defined process for when these issues get closed at this time. That should definitely change, but at present, the fact that the issue is open does not have any particular significance other than that there was a proposal that was made and that nothing has been decided. 

> I am admittedly not advanced at coding, yet I am very passionate about Ethereum, Aragon and the entire concept of blockchain technology. It is my hope that with my continued education (online classes) as well as any chances to contribute to the betterment of this or any project within Aragon that I may become as skilled a developer as I know I can be.

We have a portal for developers looking to get started with the Aragon Stack, if you haven't checked it out its here: https://hack.aragon.org -- and if you run into any issues or need help check out the #dev-help channel on aragon.chat

> I want to let you all know I will be working on this as a full time job, and if you see any way I am not fulfilling my end of things please let me know, so I may do better. Most of all thank you for the opportunity.

Just want to clarify that this issue being open does not imply an endorsement or any form of compensation for your work at this time. We do have a [grants program](https://github.com/aragon/nest) that we use to give grants for development teams building things that are useful for the Aragon Ecosystem. However, grants are given to teams based on a combination of the proposal and technical competency and so if you are just jumping into development its probably not a good fit at this time.

**Comment by AHIGHROLLER** [comment]
Very much appreciate you taking the time to set me in what looks to be a
more promising direction. I am going to go ahead and check out the first
link and again, I am a bit over the top but my intentions are good.
