### ISSUE TITLE
AGP24: Supporting aragonOS 3 DAOs on Rinkeby

### ISSUE THREAD

**Issue by sohkai** [aragon/governance#33]
# Decision

See https://github.com/aragon/governance/issues/33#issuecomment-420950051 and https://github.com/aragon/governance/issues/33#issuecomment-424056032.

-----------------------

### Goals

To what degree do we want to support old Rinkeby users when we release contracts built on aragonOS 4 alongside the mainnet release? How much effort should we spend providing a smooth migration path?

### Description

aragonOS 4 introduces a number of breaking changes from aragonOS 3. We'll be deploying these new, backwards-incompatible contracts on both Rinkeby and Mainnet together.

At the moment, most features should _just work_, but there are a few breaking changes:

- Old users won't be able to upgrade to new versions of any contracts (either internal to aragonOS, like the Kernel or ACL, or any Apps), without there being huge data problems.
- _Potentially_ ACL write functionality may not work 
 (https://github.com/aragon/aragonOS/issues/223)
- Old users won't have access to the recovery vault functionality
- Some functionality not currently exposed in the UI

As well, we are thinking of deploying completely new versions of APM, which would also increase the burden of supporting old DAOs.

Given the difficulty migrating, there's also the question of whether we should start a new root ENS registry for the new DAOs or continue reusing the old one?

---------------

### Potential paths

1. Warn the user if we detect they have a DAO older than X date, and suggest them to spin up a new DAO
2. Maintain an "old" version of Aragon Core for those users to use (e.g. `old-app.aragon.org`)
3. Ignore old DAOs, silently (or more explosively) fail if they try to access functionality

[Please suggest more :)]

**Comment by sohkai** [comment]
Given Aragon One's limited resources and prioritization, my preference is to go with option 3 along with a deprecation notice in the existing frontend to warn users of the upcoming migration.

Afterwards, a new ENS and APM will be deployed, and the frontend will stop supporting old DAOs.

**Comment by lkngtn** [comment]
Agree with 3 -- I don't think its reasonable to expect backwards compatibility or any significant migration efforts to support DAOs created in the context of a testnet release preview. Plus any effort expended in this area is effort that could be expended on more rapidly pushing towards the mainnet release. 

I think simply communicating the impact ahead of time is sufficient.

**Comment by chris-remus** [comment]
My suggestion is to - 

1 - Clearly communicate the upgrade is coming and that DAO's on the previous version won't function on the new version

2 - Provide a notice window for #1, so it doesn't happen all at once and unexpectedly

3 - Collect feedback from people who want their DAO to work on the new version

4 - Depending on the number of submissions in 3, decide whether we can help support manual migrations or if we need to do something else

**Comment by luisivan** [comment]
I'd say whatever takes less amount of work for Aragon One devs, since I'm sure no one is relaying on our Rinkeby DAOs, and if someone is, they will be close to the community and we would know after announcing the deprecation

**Comment by sohkai** [comment]
## Proposed action plan:

Silently break compatibility with old Rinkeby DAOs, and only support new aragonOS 4-powered DAOs in the new frontend.

1. Clearly communicate the upgrade is coming and that DAO's on the previous version won't function on the new version with at least a **one-month notice period**.
	- Frontend notification (a blocking modal pop up on the first load, and then leave it in the notifications panel)
	- Blog post
	- Social media
1. Collect feedback from people who want their DAO to work on the new version
	- Help any of them migrate, if necessary

------------

Decision to move forward with this will be made on **Sept. 24 at the Aragon Core Devs call**.

**Comment by izqui** [comment]
💯

If we deploy a new testnet ENS for v0.6, old DAOs will be able to work with the old versions of the apps without problem.

**Comment by chris-remus** [comment]
@izqui Would a user have to make any configuration or other choices to do that? Or, would old DAO's run w/the old app versions and new DAO's run w/the new app versions by default?

**Comment by izqui** [comment]
Old DAOs would need to be accessed through the old frontend, in the deprecation warning we would link users to go use their old DAOs in the old frontend.

**Comment by chris-remus** [comment]
@jounih See the note about the deprecation warning ^

**Comment by bpierre** [comment]
Deprecation warning issue in aragon/aragon: https://github.com/aragon/aragon/issues/364
